{ authenticated: true,
  server: 
   { options: 
      { port: 5222,
        domain: 'localhost',
        logger: true,
        websocket: [Object] },
     availableSaslMechanisms: [],
     _events: 
      { connect: [Object],
        s2sReady: [Function],
        c2sRoutersReady: [Function],
        close: [Function] },
     router: { sessions: [Object], server: [Circular], _events: [Object] },
     s2s: { ctxs: [Object] } },
  connection: 
   { streamAttrs: { version: '1.0', id: '0580057732538054', from: 'localhost' },
     xmlns: 
      { stream: 'http://etherx.jabber.org/streams',
        '': 'jabber:client' },
     socket: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 1317,
        _bytesDispatched: 1368,
        allowHalfOpen: false,
        writable: true,
        readable: true,
        _paused: false,
        server: [Object],
        _events: [Object],
        serializeStanza: [Function] },
     reconnectDelay: 0,
     parser: 
      { parser: [Object],
        bytesParsed: 990,
        maxStanzaSize: undefined,
        _events: [Object] },
     mixins: [],
     _events: 
      { streamStart: [Function],
        stanza: [Function],
        end: [Function],
        close: [Function],
        error: [Function] },
     streamNsAttrs: 
      { xmlns: 'jabber:client',
        'xmlns:stream': 'http://etherx.jabber.org/streams' },
     streamOpened: true },
  _events: 
   { online: [ [Function], [Function], [Function] ],
     end: [Function],
     stanza: 
      [ [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function] ],
     'session-started': [Function],
     'auth-success': [ [Function], [Function] ],
     'auth-failure': [Function],
     'registration-success': [Function],
     'registration-failure': [Function],
     authenticate: [Function],
     register: [Function],
     close: [Function],
     error: [Function] },
  roster: 
   { owner: 'tomburton@localhost',
     items: [],
     _events: { add: [Function] } },
  serverdomain: 'localhost',
  mechanisms: [ { username: 'tomburton' } ],
  mechanism: { username: 'tomburton' },
  username: 'tomburton',
  mongoId: 51b2860d6c4749796b000001,
  jid: 
   { user: 'tomburton',
     domain: 'localhost',
     resource: 'Fabios-MacBook-Pro' } }
Customer 51b286136c4749796b000003 online: true
presence attempt: <presence xmlns:stream="http://etherx.jabber.org/streams" from="bobby@localhost" xmlns="jabber:client" to="tomburton@localhost"><show>online</show></presence>
{ authenticated: true,
  server: 
   { options: 
      { port: 5222,
        domain: 'localhost',
        logger: true,
        websocket: [Object] },
     availableSaslMechanisms: [],
     _events: 
      { connect: [Object],
        s2sReady: [Function],
        c2sRoutersReady: [Function],
        close: [Function] },
     router: { sessions: [Object], server: [Circular], _events: [Object] },
     s2s: { ctxs: [Object] } },
  connection: 
   { streamAttrs: { version: '1.0', id: '0889970065943829', from: 'localhost' },
     xmlns: 
      { stream: 'http://etherx.jabber.org/streams',
        '': 'jabber:client' },
     socket: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 1817,
        _bytesDispatched: 2644,
        allowHalfOpen: false,
        writable: true,
        readable: true,
        _paused: false,
        server: [Object],
        _events: [Object],
        serializeStanza: [Function] },
     reconnectDelay: 0,
     parser: 
      { parser: [Object],
        bytesParsed: 1521,
        maxStanzaSize: undefined,
        _events: [Object] },
     mixins: [],
     _events: 
      { streamStart: [Function],
        stanza: [Function],
        end: [Function],
        close: [Function],
        error: [Function] },
     streamNsAttrs: 
      { 'xmlns:stream': 'http://etherx.jabber.org/streams',
        xmlns: 'jabber:client',
        'xmlns:xml': 'http://www.w3.org/XML/1998/namespace' },
     streamOpened: true },
  _events: 
   { online: [ [Function], [Function], [Function] ],
     end: [Function],
     stanza: 
      [ [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function] ],
     'session-started': [Function],
     'auth-success': [ [Function], [Function] ],
     'auth-failure': [Function],
     'registration-success': [Function],
     'registration-failure': [Function],
     authenticate: [Function],
     register: [Function],
     close: [Function],
     error: [Function] },
  roster: 
   { owner: 'bobby@localhost',
     items: [],
     _events: { add: [Function] } },
  serverdomain: 'localhost',
  mechanisms: [ { username: 'bobby' } ],
  mechanism: { username: 'bobby' },
  username: 'bobby',
  mongoId: 51b798d8b172730000000001,
  jid: 
   { user: 'bobby',
     domain: 'localhost',
     resource: 'Fabios-MacBook-Pro' } }